language: rust
rust:
  - stable

os: 
  - linux
    dist: bionic
  - windows

cache: cargo
before_install:
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo apt update; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo apt install -y pkg-config libzmq3-dev libssl-dev; fi

jobs:
  include:
  - stage: build
    os: linux
    script:
      cargo build --verbose
  - stage: unittest
    os: linux
    script:
    - cargo test bitcoin
    - cargo test crypto
    - cargo test db
  - stage: regtest
    os: linux
    if: os = linux
    script:
    - sudo add-apt-repository -y ppa:bitcoin-abc/ppa
    - sudo apt-get update
    - sudo apt install -y libzmq3-dev
    - sudo apt install -y bitcoind
    - bitcoind -daemon -regtest -zmqpubrawtx=tcp://127.0.0.1:28332 -rpcallowip=0.0.0.0/0 -server -rpcuser=username -rpcpassword=password
    - sleep 30
    - bitcoin-cli -regtest -rpcuser=username -rpcpassword=password generate 101
    - cargo test
  